little u.i modifications
Meghatronics/Peek-Up pull request #2
Opened 2020-06-16 08:27 UTC by triggac4

just a few ui changes including the circularprogressindicator() to display when loading and snackbar that shows when an error occurs

2020-06-16 11:39 UTC, Meghatronics commented
Your additions to the network handler for error handling are great!

2020-06-16 11:43 UTC, Meghatronics requested changes
Please revert the Home State class to its original form.

Then replace only the 
`Text( '. . .',   style: kGreetingTextStyle, ),` with the *CircularProgressIndicator()*

2020-06-17 02:04 UTC, triggac4 commented
done and done

2020-06-17 13:25 UTC, Meghatronics approved these changes

2020-06-17 13:26 UTC, merged